### Testing the GET /api/events endpoint
GET  http://localhost:7777/api/events

### Testing the GET /api/events/:id endpoint with a non-existent ID
GET http://localhost:7777/api/events/does-not-exist


### Testing the POST /api/events endpoint
POST http://localhost:7777/api/events
Content-Type: application/json

{
  "title": "Classic Cars Exhibition",
  "description": "A meetup for car lovers in Addis",
  "date": "2026-10-20",
  "location": "Addis Ababa",
  "capacity": 150
}

### Testing the GET /api/events/:id endpoint
GET http://localhost:7777/api/events/64e8f1b2c9a1f2b3d4e5f6a7

### Testing the POST/PUT /api/events/:id endpoint
PUT http://localhost:7777/api/events/6aa15366295f47097bfdbc69
Content-Type: application/json

{
  "title": "Addis Car Meetup V0.2",
  "description": "An updated meetup for car lovers in Addis Ababa",
  "date": "2026-10-20",
  "location": "Addis Ababa",
  "capacity": 99
}

### Testing the DELETE /api/events/:id endpoint
DELETE http://localhost:7777/api/events/6aa0758957ed9c7cafd915d0